name: ${project.name}
description: ${project.description}
main: org.retromc.jcode.JCode
version: ${project.version}
authors:
  - JohnyMuffin

commands:
  jcode:
    description: A command utilized to generate JCodes
    usage: /<command> [args]
    permission: jcode.code